version: '3.8'

services:
  nest-api:
    mem_limit: 2g
    cpus: 2.0
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - ./tmp:/tmp
    command: sh -c "rm -rf /tmp/* && npm run start:dev"
    depends_on:
      - minio
      - redis
    networks:
      - appnet

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    env_file:
      - .env.docker
    command: server /data --console-address ":9001"
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6380:6379'
    networks:
      - appnet
    volumes:
      - redis-data:/data

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./k6-test:/mnt/k6-test
    working_dir: /mnt/k6-test
    entrypoint: ['sleep', 'infinity']
    depends_on:
      - nest-api
    networks:
      - appnet
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  appnet:
    driver: bridge

volumes:
  redis-data:
